name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      
      - name: Clone Hexo theme manually
        run: |
          rm -rf themes/butterfly
          git clone --depth=1 https://github.com/jerryc127/hexo-theme-butterfly.git themes/butterfly

      - name: Install dependencies
        run: |
          npm install
          npm install hexo-cli -g
          npm install hexo-deployer-git --save

      - name: Configure Git
        run: |
          git config --global user.name "HqSelene"
          git config --global user.email "hqselene@163.com"

      - name: Generate and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hexo clean
          hexo generate
          hexo deploy