name: 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update --remote --recursive